/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gymMain;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Date;

/**
 *
 * @author jx
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form UserLogin
     */
    private int memberId;
    public AdminLogin() {
        initComponents();
        Clear.setOpaque(false);
        //Clear.setContentAreaFilled(false);
        //Clear.setBorderPainted(false);
        
        Login1.setOpaque(false);
        //Login1.setContentAreaFilled(false);
        //Login1.setBorderPainted(false);
        
        memberLogin.setOpaque(false);
        //registerButton.setContentAreaFilled(false);
        //registerButton.setBorderPainted(false);
    }
    
    Connection Con;
    Statement St;
    ResultSet Rs;
    PreparedStatement Pst;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/gymba", "root", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UserProfile.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(UserProfile.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        katas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();
        showPassword = new javax.swing.JCheckBox();
        Password = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        Login1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        memberLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 400));
        jPanel1.setLayout(null);

        katas.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setText("Gym Management");

        javax.swing.GroupLayout katasLayout = new javax.swing.GroupLayout(katas);
        katas.setLayout(katasLayout);
        katasLayout.setHorizontalGroup(
            katasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(katasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(656, Short.MAX_VALUE))
        );
        katasLayout.setVerticalGroup(
            katasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(katasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(katas);
        katas.setBounds(0, 0, 870, 60);

        Username.setToolTipText("");
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        jPanel1.add(Username);
        Username.setBounds(167, 185, 178, 42);

        Clear.setBackground(new java.awt.Color(204, 255, 255));
        Clear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Clear.setText("Clear Text");
        Clear.setToolTipText("");
        Clear.setFocusable(false);
        Clear.setName(""); // NOI18N
        Clear.setOpaque(true);
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearMouseClicked(evt);
            }
        });
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear);
        Clear.setBounds(150, 340, 100, 50);

        showPassword.setBackground(new java.awt.Color(204, 255, 255));
        showPassword.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        showPassword.setText("Show Password");
        showPassword.setFocusable(false);
        showPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showPasswordMouseClicked(evt);
            }
        });
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(showPassword);
        showPassword.setBounds(200, 309, 110, 20);
        jPanel1.add(Password);
        Password.setBounds(167, 254, 178, 40);

        jLabel6.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLabel6.setText("ADMIN LOGIN");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 120, 260, 39);

        Login1.setBackground(new java.awt.Color(204, 255, 255));
        Login1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Login1.setText("Login");
        Login1.setFocusable(false);
        Login1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Login1MouseClicked(evt);
            }
        });
        Login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login1ActionPerformed(evt);
            }
        });
        jPanel1.add(Login1);
        Login1.setBounds(260, 340, 90, 50);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel4.setText("PASSWORD");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(29, 254, 130, 40);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel5.setText("USERNAME");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(29, 185, 130, 40);

        memberLogin.setBackground(new java.awt.Color(204, 255, 255));
        memberLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        memberLogin.setText("Member Login");
        memberLogin.setFocusable(false);
        memberLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memberLoginMouseClicked(evt);
            }
        });
        memberLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberLoginActionPerformed(evt);
            }
        });
        jPanel1.add(memberLogin);
        memberLogin.setBounds(680, 410, 160, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        
    }//GEN-LAST:event_ClearActionPerformed

    private void ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseClicked

        Username.setText("");
        Password.setText("");
    }//GEN-LAST:event_ClearMouseClicked

    private void showPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPasswordMouseClicked
        if (evt.getSource() == showPassword) {
            if (showPassword.isSelected()) {
                Password.setEchoChar((char) 0);
            }
            else {
                Password.setEchoChar('*');
            }
        }
    }//GEN-LAST:event_showPasswordMouseClicked

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showPasswordActionPerformed

    private void Login1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login1MouseClicked
        String userName = Username.getText();
        
        if(Username.getText().isEmpty()||Password.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
        String Query = "select * from adminlogin where username= '"+Username.getText()+"' and password='"+Password.getText()+"'";        
        try {
            Con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/gymba", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery(Query);
            Connect();
            if(Rs.next()) {
                
                JOptionPane.showMessageDialog(this, "Welcome " + userName);
                new AdminCurrentMember(memberId).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Wrong username or password");
            }
        }
            catch(Exception e) 
            {
            e.printStackTrace();
            }
        }
    }//GEN-LAST:event_Login1MouseClicked

    private void Login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login1ActionPerformed

    private void memberLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberLoginMouseClicked
        new UserLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_memberLoginMouseClicked

    private void memberLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Login1;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel katas;
    private javax.swing.JButton memberLogin;
    private javax.swing.JCheckBox showPassword;
    // End of variables declaration//GEN-END:variables

    private static class DriverManager {

        public DriverManager() {
        }
    }
}
