/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gymMain;

import java.sql.*;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import java.util.*;
import net.proteanit.sql.DbUtils;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.*;
import javax.swing.RowFilter;
import java.sql.Date;
//import net.proteanit.sql.DbUtils;


/**
 *
 * @author jx
 */



public class UserGymClass extends javax.swing.JFrame {

    /**
     * Creates new form Product
     */
    private int memberid;
    
    public UserGymClass(int memberid) {
        this.memberid = memberid;
        initComponents();
        Connect();
        SelectProd();
        //findUsers();
        searchAlgo();
        
        //Clear.setOpaque(false);
        //Clear.setContentAreaFilled(false);
        //Clear.setBorderPainted(false);
        
        /*
        unselect.setOpaque(false);
        unselect.setContentAreaFilled(false);
        unselect.setBorderPainted(false);
        */
        
        Logout.setOpaque(false);
        //Logout.setContentAreaFilled(false);
        //Logout.setBorderPainted(false);
        
        Enroll.setOpaque(false);
        //Add.setContentAreaFilled(false);
        //Add.setBorderPainted(false);
        
        //Clear.setOpaque(false);
        //Clear.setContentAreaFilled(false);
        //Clear.setBorderPainted(false);
        
        //Delete.setOpaque(false);
        //Delete.setContentAreaFilled(false);
        //Delete.setBorderPainted(false);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;
    PreparedStatement Pst = null;

    
    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gymba", "root", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UserGymClass.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(UserGymClass.class.getName()).log(Level.SEVERE, null, ex);
        } 
}
    
    
    private void enrollInClass() {
    int selectedRow = gymClassTable.getSelectedRow();
    if (selectedRow != -1) {
        int classId = (int) gymClassTable.getValueAt(selectedRow, 0);
        try (Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gymba", "root", "")) {
            

            String checkQuery = "SELECT * FROM Enrollments WHERE member_id = ? AND class_id = ?";
            PreparedStatement checkStmt = Con.prepareStatement(checkQuery);
            checkStmt.setInt(1, memberid);  
            checkStmt.setInt(2, classId);
            ResultSet rs = checkStmt.executeQuery();

            if (rs.next()) {

                JOptionPane.showMessageDialog(this, "You are already enrolled in this class!");
            } else {
    
                PreparedStatement enrollStmt = Con.prepareStatement("INSERT INTO Enrollments (member_id, class_id) VALUES (?, ?)");
                enrollStmt.setInt(1, memberid);
                enrollStmt.setInt(2, classId);
                enrollStmt.executeUpdate();


                PreparedStatement updateSpotsStmt = Con.prepareStatement("UPDATE Classes SET available_spots = available_spots - 1 WHERE class_id = ?");
                updateSpotsStmt.setInt(1, classId);
                updateSpotsStmt.executeUpdate();


                JOptionPane.showMessageDialog(this, "Successfully enrolled in the class!");
                ((DefaultTableModel) gymClassTable.getModel()).removeRow(selectedRow); 
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a class to enroll in.");
    }
}
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        unselect = new javax.swing.JButton();
        searchBox = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gymClassTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        Enroll = new javax.swing.JButton();
        Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 200, 221));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel5.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 36)); // NOI18N
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        unselect.setBackground(new java.awt.Color(204, 255, 255));
        unselect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymMain/check.png"))); // NOI18N
        unselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unselectActionPerformed(evt);
            }
        });

        searchBox.setToolTipText("");
        searchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(204, 255, 255));
        searchButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchButton.setText("SEARCH");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        profileButton.setBackground(new java.awt.Color(204, 255, 255));
        profileButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        profileButton.setText("Profile");
        profileButton.setToolTipText("");
        profileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileButtonMouseClicked(evt);
            }
        });
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel4.setText("Gym Management");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addGap(101, 101, 101)
                .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButton)
                .addGap(30, 30, 30)
                .addComponent(unselect, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel5)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(unselect, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(32, 32, 32))
        );

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        gymClassTable.setAutoCreateRowSorter(true);
        gymClassTable.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        gymClassTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "class_id", "class_day", "class_name", "start_time", "end_time", "instructor", "available_spots"
            }
        ));
        gymClassTable.setShowGrid(false);
        gymClassTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gymClassTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gymClassTable);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("Available Classes");

        Enroll.setBackground(new java.awt.Color(204, 255, 255));
        Enroll.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Enroll.setText("Enroll");
        Enroll.setToolTipText("");
        Enroll.setFocusable(false);
        Enroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnrollMouseClicked(evt);
            }
        });
        Enroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrollActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(204, 255, 255));
        Logout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Logout.setText("Logout");
        Logout.setToolTipText("");
        Logout.setFocusable(false);
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 104, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Logout)
                        .addGap(314, 314, 314)
                        .addComponent(Enroll, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enroll, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void SelectProd() {
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gymba", "root", "");
            St = Con.createStatement();
            Rs = (ResultSet) St.executeQuery("select * from classes");
            gymClassTable.setModel(DbUtils.resultSetToTableModel(Rs));
        } catch (SQLException ex) {
            ex.printStackTrace();
            Logger.getLogger(UserGymClass.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public ArrayList<User> ListUser(String ValToSearch) {
        ArrayList<User> usersList = new ArrayList<User>();
        
        Statement St;
        ResultSet rs;
        
        try{
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gymba", "root", "");
            St = Con.createStatement();
            String searchQuery = "select * from `classes` where CONCAT(`class_id`, `class_day`, `class_name`, `start_time`, `end_time`, `instructor`, `available_spots`) LIKE '%" + ValToSearch + "%'";
            rs = St.executeQuery(searchQuery);
            
            User user;
            
            while(rs.next()) {
                user = new User(rs.getInt("class_id"),
                                rs.getString("class_day"),
                                rs.getString("class_name"),
                                rs.getString("start_time"),
                                rs.getString("end_time"),
                                rs.getString("instructor"),
                                rs.getInt("available_spots")
                                );
                usersList.add(user);
            }
        }catch (SQLException ex) {
            ex.printStackTrace();
            Logger.getLogger(UserGymClass.class.getName()).log(Level.SEVERE, null, ex);
    }
        return usersList;
    }
    
    
    
    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void gymClassTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gymClassTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)gymClassTable.getModel();
        int Myindex = gymClassTable.getSelectedRow();
        //ContainerID.setText(model.getValueAt(Myindex, 0).toString());
        //customerName.setText(model.getValueAt(Myindex, 1).toString());
        //customerAddress.setText(model.getValueAt(Myindex, 2).toString());
        //orderStatus.setText(model.getValueAt(Myindex, 3).toString());
    }//GEN-LAST:event_gymClassTableMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        new UserLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void unselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unselectActionPerformed
        gymClassTable.getSelectionModel().clearSelection();
    }//GEN-LAST:event_unselectActionPerformed

    private void searchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBoxActionPerformed

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonMouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        searchAlgo();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void EnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnrollActionPerformed

    private void EnrollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnrollMouseClicked
        enrollInClass();
    }//GEN-LAST:event_EnrollMouseClicked

    private void profileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileButtonMouseClicked
        new UserProfile(memberid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileButtonMouseClicked

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UserGymClass(int memberid).setVisible(true);
//            }
//        });
    }
    
    
        public void searchAlgo() {
        ArrayList<User> users = ListUser(searchBox.getText());
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"Class ID","Class Day","Class Name","Start Time","End Time","Instructor","Available Spots"});
        Object[] row = new Object[7];
        
        for(int i = 0; i < users.size(); i++){
            row[0] = users.get(i).getclass_id();
            row[1] = users.get(i).getclass_day();
            row[2] = users.get(i).getclass_name();
            row[3] = users.get(i).getstart_time();
            row[4] = users.get(i).getend_time();
            row[5] = users.get(i).getinstructor();
            row[6] = users.get(i).getavailable_spots();
            model.addRow(row);
    }
    gymClassTable.setModel(model);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enroll;
    private javax.swing.JButton Logout;
    private javax.swing.JTable gymClassTable;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton profileButton;
    private javax.swing.JTextField searchBox;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton unselect;
    // End of variables declaration//GEN-END:variables

    


    
}
